/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lda_jni_Utils */

#ifndef _Included_lda_jni_Utils
#define _Included_lda_jni_Utils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lda_jni_Utils
 * Method:    warpOneIter
 * Signature: (IIIII[I[I[I[I[I[I[B[S[SIDDD)D
 */
JNIEXPORT jdouble JNICALL Java_lda_jni_Utils_warpOneIter
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jshortArray, jshortArray, jint, jdouble, jdouble, jdouble);

/*
 * Class:     lda_jni_Utils
 * Method:    warpInit
 * Signature: (III[I[I[I[I[S[SI)D
 */
JNIEXPORT jdouble JNICALL Java_lda_jni_Utils_warpInit
  (JNIEnv *, jclass, jint, jint, jint, jintArray, jintArray, jintArray, jintArray, jshortArray, jshortArray, jint);

#ifdef __cplusplus
}
#endif
#endif
